CREATE TABLE IF NOT EXISTS status_animal(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL UNIQUE CHECK (nome IN ('DISPONIVEL PARA ADOCAO','EM TRATAMENTO','EM QUARENTENA', 'ADOTADO','RECEM-RESGATADO','FALECIDO')),
	devolvido BOOLEAN DEFAULT FALSE,
	dt_atualizacao TIMESTAMP DEFAULT NOW()
);