CREATE TABLE IF NOT EXISTS status_animal(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL UNIQUE CHECK (nome IN ('DISPONIVEL_PARA_ADOCAO','EM_TRATAMENTO','EM_QUARENTENA', 'ADOTADO','RECEM_RESGATADO',
	                                                 'FALECIDO')),
	devolvido BOOLEAN DEFAULT FALSE,
	dt_atualizacao TIMESTAMP DEFAULT NOW()
);