ALTER TABLE animal
ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE adotante
ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE raca
ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
